<?php

use Illuminate\Database\Seeder;

class LanguageTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('nh_language')->insert(
            [
                ['language' => 'de', 'default_language' => true, 'published' => false, 'disabled' => false],
                ['language' => 'en', 'default_language' => false, 'published' => false, 'disabled' => false],
                ['language' => 'aa', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ab', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'af', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'am', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ar', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'as', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ay', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'az', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ba', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'be', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'bg', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'bh', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'bi', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'bn', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'bo', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'br', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ca', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'co', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'cs', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'cy', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'da', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'dz', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'el', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'eo', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'es', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'et', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'eu', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'fa', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'fi', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'fj', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'fo', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'fr', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'fy', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ga', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'gd', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'gl', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'gn', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'gu', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ha', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'hi', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'hr', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'hu', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'hy', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ia', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ie', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ik', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'in', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'is', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'it', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'iw', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ja', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ji', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'jw', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ka', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'kk', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'kl', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'km', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'kn', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ko', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ks', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ku', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ky', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'la', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ln', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'lo', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'lt', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'lv', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'mg', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'mi', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'mk', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ml', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'mn', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'mo', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'mr', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ms', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'mt', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'my', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'na', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ne', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'nl', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'no', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'oc', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'om', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'pa', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'pl', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ps', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'pt', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'qu', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'rm', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'rn', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ro', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ru', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'rw', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'sa', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'sd', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'sg', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'sh', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'si', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'sk', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'sl', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'sm', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'sn', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'so', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'sq', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'sr', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ss', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'st', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'su', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'sv', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'sw', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ta', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'te', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'tg', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'th', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ti', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'tk', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'tl', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'tn', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'to', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'tr', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ts', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'tt', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'tw', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'uk', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'ur', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'uz', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'vi', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'vo', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'wo', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'xh', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'yo', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'zh', 'default_language' => false, 'published' => false, 'disabled' => true],
                ['language' => 'zu', 'default_language' => false, 'published' => false, 'disabled' => true],
            ]
        );
    }
}
